export const DOCTORS = [
  {
    id: 1,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
  {
    id: 2,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
  {
    id: 3,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
  {
    id: 4,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
  {
    id: 5,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
  {
    id: 6,
    slug: 'slug',
    category: 'Hair Transplant',
    name: 'Dr. Emrah Cinik, MD',
    image: '/images/doctors/doctor.png',
    location: 'Istanbul, Turkey',
    qunoScore: 9.4,
    numberOfReviews: 190,
    rating: 4.8,
    numberOfTreatmentsInLastYear: 1270,
    yearsOfExperience: 5,
    startFrom: 2.09,
  },
];
